name: 1 - Test Django

on:
  workflow_dispatch:
  push:
    branches: [main]
  
jobs:
  django_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Django Tests
        run: python manage.py test     
